### ISSUE TITLE
Check adresses before showing Notary or RKH view

### ISSUE THREAD

**Issue by josepablofm78** [keyko-io/filecoin-verifier-frontend#125]
currently all the users are able to access to the RKH or Notary View.
to avoid this, we need to check the addresses of the wallet selected and see of there is an address added as RKH or Notary.  
additionally we can change the flow a little bit to force the users the address they want to use as RKH or Notary and check than one

**Comment by fabriziogianni7** [comment]
done, the user can access both notary or RKH view, but if he has not the right permissions, he cannot take action
