### ISSUE TITLE
Remove Notaries in RKH View

### ISSUE THREAD

**Issue by josepablofm78** [keyko-io/filecoin-verifier-frontend#222]
when the approved comment from github issue has a zero number, like this one: 

https://github.com/filecoin-project/notary-governance/issues/87#issuecomment-763674025

the frontend app must call the new removeVerifier method introduced in filecoin-verifier-tools v1.3.5  when the RKH uses the Sign On-chain to propose the tx

**Comment by fabriziogianni7** [comment]
@ialberquilla I think this is done already,  right?
