### ISSUE TITLE
[ Bug Report ]

### ISSUE THREAD

**Issue by dannyob** [keyko-io/filecoin-verifier-frontend#401]
**Describe the bug**

A notary approving  a large request clears the 'public requests' and 'large request' lists, which means that the notary has to log in from scratch, rather than just move onto the next large request.

**To Reproduce**
After a notary approves a large client allocation (by clicking on the Large Request Tab, selecting a request, and clicking "Approve Request"

1. Log in as a notary.
2. Click on 'Large Request' tab
3. Select a request.
4. Click Approve request.
5. Sign approval.
6. Message will appear showing transaction has been sent.
7. Large and Public request tabs will be suffixed with '(0)' showing that no items are in either list. The displayed Large Request table will also be empty.

**Expected behavior**
The request lists should continue to show other requests, so that the notary can continue to work on them without re-logging in.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Brave
 - Version [Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by fabriziogianni7** [comment]
Thank you @dannyob , we will check this soon

**Comment by fabriziogianni7** [comment]
@dannyob 
We made some release.
can you see if you still encounter the problem?

**Comment by fabriziogianni7** [comment]
solved with the next release
