### ISSUE TITLE
Log-in with github when verifying wallet

### ISSUE THREAD

**Issue by fabriziogianni7** [keyko-io/filecoin-verifier-frontend#428]
## Main description
Seems that the reason related to the missing verification comment on the notary-governance repo is that who is signing the message is not logged with github.
Inserting a step where the notary has to sign in with github before signing the transaction.

## TODOs
implement the logic to log in with github when notary is verifying the wallet.

### Behavior:
**if notary is not logged in with github:**
when click to approve request
show, in the pop-up a button to login in github and text explaining that they need to log in to verify the wallet

**if notary is already logged:**
the flow is as usual

**Comment by galen-mcandrew** [comment]
For subsequent sign-ins, is this tool checking that an address has already been verified (and therefore can move on to send allocations) by looking for either a) comment from the bot in a github issue, such as https://github.com/filecoin-project/notary-governance/issues/422#issuecomment-1125732012 **OR** b) looking on chain for an existing message between the signed-in address and the destination address?
