### ISSUE TITLE
[ Bug Report ]  Login fails at entering the page

### ISSUE THREAD

**Issue by fabriziogianni7** [keyko-io/filecoin-verifier-frontend#454]
The first time you log in the application, you got the message 'something went wrong, please try again'
The login is failing.
May be a problem with github login.
Need to investingate and understand why this happen

**Comment by smagdali** [comment]
Just in case we're not talking about the same thing, I was on https://plus.fil.org/verifiers, trying to request datacap. 

I recorded the experience here: 

https://www.dropbox.com/s/j48cx76mo6ofw8r/Datacap%20request%20problem.mov?dl=0

**Comment by fabriziogianni7** [comment]
thank you for the contribution @smagdali !! we will take care of this ASAP! 💥💥

**Comment by dannyob** [comment]
Sorry for the comment spam -- on the bright side, we now know that the error doesn't actually stop the request from being logged, which I think implies that it's a transitory/nonfatal github login error. Maybe we're misreading the initial login reply?

(The screenshot shows all of @smagdali's requests which went through despite the login failure error message.)

![multiplestefs](https://user-images.githubusercontent.com/227660/174410515-010eb8f3-fee1-473f-908a-3f901c9bfc17.png)

**Comment by fabriziogianni7** [comment]
Ok, This looks like another problem. 
this issue is about the login in the notary dashboard that sometimes is failing

I opened this issue #506 for the general verification.

**Comment by fabriziogianni7** [comment]
https://github.com/keyko-io/filecoin-verifier-frontend/issues/506

**Comment by huseyincansoylu** [comment]
hey thank you for the contribution and the video @smagdali !! , I wonder if you can send me another video with the console open?

**Comment by smagdali** [comment]
Here it is with the console open.

https://www.dropbox.com/s/6bubzw2nla41jqs/with%20Console%202022-08-04%20at%2012.10.43.mov?dl=0

**Comment by smagdali** [comment]
Interestingly, that last request, is the only one I have ever received an acknowledgement for 

https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2283#issuecomment-1205112587
