### ISSUE TITLE
[ New Feature ] - Create a new tab in NOTARY dashboard for canceling duplicate proposals

### ISSUE THREAD

**Issue by fabriziogianni7** [keyko-io/filecoin-verifier-frontend#543]
## Main description
Create a new tab in NOTARY dashboard for canceling duplicate proposals

### Additional context
In order to cancel the duplicate proposals, we can create a new tab in the RKH view to let NOTARY sign the cancel transactions for the selected github comments.
the transactions to cancel are essentially github comment posted for mistake. we should mark those comments with "to cancel" to show them in the tab

### The tab:
The tab should be named "duplicate requests"
It should be filled with all the pending proposals that are created for mistake.
The code should then go through all the github repo and retrieve all the github comment marked with "to cancel"  and show the data in the table
We need to add a button "cancel proposal" to cancel the transaction

#### Data in each row
each item in the table should contain **issue number, client name, tx id, client address and datacap.**

### How do we mark those comments with "to cancel" flag ?
We can do it either manually or we can try to find other solution. for now we can create some test case using test repo and then we can expand on it

### How we actually cancel the proposals
After clicking the button, we should call the following function in filecoin-verifier-tools.
In filecoin-verifier-tools there is a function for that: [cancelPenidng](https://github.com/keyko-io/filecoin-verifier-tools/blob/38fbbdebf5103e26449a3bf45efcc55b1c3f2053/api/api.js#L241)

### What should happen after we successfully cancel a proposal?
the comment on github can be deleted or remarked with "canceled". we can discuss about this with PL team

**Comment by fabriziogianni7** [comment]
@huseyincansoylu this is an update after recent talk with governance team:
# Update

The tab should be in the NOTARY dashboard;
We are not going to mark any issue with to cancel
we are going to show all the transactions proposed by the address who is logged in

## The tab
the tab should contain all the transactions proposed by the notary and should have the possibility to select one transaction at the time to be canceled.
once the user selects the row, he can click on a button 'cancel proposal1 to cancel it.
each row in the table should contain issue number, client name, tx id, client address and datacap.

## retrieving pending transaction
[We are not going to mark any issue with to cancel. instead we need to retrieve all the pending transaction and filter for signers. here is the function you need to use --> [pendingTransction](https://github.com/keyko-io/filecoin-verifier-tools/blob/4ba9421bcb1dd7b8f8e8bc144497c4ab92afe3de/api/api.js#L301)
You need to pass there the multisig address they are logged with, here is an example of how to fetch transactions using msig user are logged with ---> [example](https://github.com/keyko-io/filecoin-verifier-frontend/blob/30d9ba5cddf8097b4260f408834bb4deb2381115/src/context/Data/DataProvider.tsx#L204)

**Comment by huseyincansoylu** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> t01021

#### Client address
> t1rbfyvybljzd5xcouqjx22juucdj3xbwtro2crwq

#### DataCap allocation requested
> 50TiB

**Comment by huseyincansoylu** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> t1rbfyvybljzd5xcouqjx22juucdj3xbwtro2crwq
