### ISSUE TITLE
remove sass package

### ISSUE THREAD

**Issue by fabriziogianni7** [keyko-io/filecoin-verifier-frontend#582]
- [ ] update node js (moved to issue #605)
- [x] remove sass package

**Comment by fabriziogianni7** [comment]
@jbesraa you want to start with that?

**Comment by fabriziogianni7** [comment]
and afterwards, you could do that --> #583

**Comment by jbesraa** [comment]
was able to upgrade sass package but not to pump node version from 14. other packages beside sass needs inspection before upgrading the node version, including react-scripts which was upgraded to v4 but and not v5 as the latest introduced many errors.
