### ISSUE TITLE
Multiple comments on general application issues

### ISSUE THREAD

**Issue by Lord-Bach** [keyko-io/filecoin-verifier-frontend#754]
**Describe the bug**
Multiplying the number of comments for each issue and removes the source:filplus.storage label.

**To Reproduce**
Go to https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2753 or any issues in https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues

Scroll down to were the comments that the filecoin-on-boarding-bot creates. Issues have over 100+ comments that are not helpful.

**Screenshots**
![Screenshot 2023-05-05 at 12 18 55 PM](https://user-images.githubusercontent.com/59632896/236515227-388c1528-56b0-4573-a290-8bd343be256d.png)

**Comment by fabriziogianni7** [comment]
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2757
the issue seems resolved.
I had to restart the AWS instance.
Still not sure why that's happened.

closing it
