### ISSUE TITLE
[ Bug Report ] missing uuid in proposals/ approvals

### ISSUE THREAD

**Issue by smooth-operator** [keyko-io/filecoin-verifier-frontend#758]
**Describe the bug**
The uuid allowance is missing from Request Approved and Request Proposed comments.

Example:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1264#issuecomment-1541429654
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1965#issuecomment-1541340729
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1653#issuecomment-1543366570

**Comment by fabriziogianni7** [comment]
@smooth-operator is this still happening?

**Comment by smooth-operator** [comment]
yes these 2 comments are posted yesterday:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1476#issuecomment-1552674973
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1476#issuecomment-1552793448

**Comment by smooth-operator** [comment]
Now the uuid appears as `not found`:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1848#issuecomment-1556089514
We receive the same through the api.

**Comment by fabriziogianni7** [comment]
should be resolved with this PR: https://github.com/keyko-io/filecoin-verifier-frontend/pull/765
