### ISSUE TITLE
[ Bug Report ] test environment in events sent to Dmob

### ISSUE THREAD

**Issue by smooth-operator** [keyko-io/filecoin-verifier-frontend#759]
**Describe the bug**
datacap_allocation bot events sent to datacapstats.io are being sent with env test instead of prod.

![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/4047772/5a740ff5-5c14-43bf-9f8f-f6b09b39fc2a)

**Comment by fabriziogianni7** [comment]
@smooth-operator is this resolved?

**Comment by smooth-operator** [comment]
no, it's still happening
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/4047772/5667be62-d32f-43e9-ab67-8b00b623310d)

**Comment by smooth-operator** [comment]
all is sorted
