### ISSUE TITLE
Still get the previous datacap info when approving a new request 

### ISSUE THREAD

**Issue by max1015070108** [keyko-io/filecoin-verifier-frontend#770]
**Describe the bug**
Still get the previous datacap info when approving a new request 

**To Reproduce**
1. go to plus.fil.org and approve an request by using searching form
2. finish this request approve and make sure it has been included in blockchain 
3.  not fresh the website and then search another one you want to approve
3. then you will seen previous one on the screen 

**Expected behavior**
The request info should be as the same with the one you want 

**Screenshots**
![](https://files.slack.com/files-pri/TEHTVS1L6-F05A0FZTHFU/image.png)

**Desktop (please complete the following information):**
 - Browser [chrome]
 chrome

**Additional context**
https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1681709822382039

**Comment by fabriziogianni7** [comment]
thanks for flagging. we are on it

**Comment by jbesraa** [comment]
hey @max1015070108 @fabriziogianni7 was this resolved?

**Comment by clriesco** [comment]
Closed due to inactivity
