### ISSUE TITLE
[ Bug Report ] Negative Datacap

### ISSUE THREAD

**Issue by panges2** [keyko-io/filecoin-verifier-frontend#771]
**Describe the bug**
Stats showing "negative datacap" remaining

**Additional context**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1838#issuecomment-1575420141

**Comment by fabriziogianni7** [comment]
should be fixed with this PR --> https://github.com/keyko-io/filecoin-auto-datacap-allocation-bot/pull/105
