### ISSUE TITLE
[The bot's error caused the second notary unable to sign.]

### ISSUE THREAD

**Issue by StoneMoonGalaxy** [keyko-io/filecoin-verifier-frontend#772]
**Describe the bug**
The bot's error message caused the second notary unable to sign.

**Detailed description**
When I contacted the notary to sign the second signature, they said that our application was not in their backend system, and they could not sign it. Please refer to [#1760](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1760).

**Screenshots**
<img width="512" alt="20230607133606" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/114480622/d7b639bf-fef4-454c-99e2-849e20a3df84">

**Comment by fabriziogianni7** [comment]
the comment in the picture is old, this bug should be fixed now. closing
