### ISSUE TITLE
[ Bug Report ] 1880 has no proposal but has approved message. The SSA bot changed it to granted

### ISSUE THREAD

**Issue by panges2** [keyko-io/filecoin-verifier-frontend#775]
**Describe the bug**

**Additional context**
https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1681796194190079?thread_ts=1681726544.962769&cid=C01DLAPKDGX

**Comment by fabriziogianni7** [comment]
closing cause the bug is old and should be ok now. feel free to reopen if it's happening again
