### ISSUE TITLE
Deleting command on LDN applications is not working

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#777]
**Describe the bug**
After deleting a notary request, the bot recognized the comment and another notary was still able to provide an approval for DataCap. The  

**To Reproduce**
1. Go to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1968#issuecomment-1590892442
2. See comment made by newwebgroup where the notary approved the request.

**Expected behavior**
After deleting a notary request signature on the LDN application, the application should not be able to receive an approval.

**Screenshots**
Check history of this application. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1968#issuecomment-1590892442

**Comment by fabriziogianni7** [comment]
@simonkim0515 not sure what we mean with removal, could you be more specific?

**Comment by jbesraa** [comment]
hey @simonkim0515 is this still an issue?
