### ISSUE TITLE
very large application label showing on applications under 5PiB

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#778]
**Describe the bug**
The very large application label is showing on applications under 5PiB and the label should only be showing on applications over 5PiB.

**To Reproduce**
1. Recreate a test application under 5 PiB

**Expected behavior**

**Screenshots**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2064

**Comment by fabriziogianni7** [comment]
should be solved
