### ISSUE TITLE
[ Bug Report ] Client Address for LDN has incorrect characters

### ISSUE THREAD

**Issue by jamerduhgamer** [keyko-io/filecoin-verifier-frontend#780]
**Describe the bug**
Address has some characters in it that should not be there as seen in the screenshot below compared to the other addresses.

**To Reproduce**
1. Go to filplus.fil.org
2. Click on "For Root Key Holders and Notaries"
3. Click on "Log in as a Notary" (will need your Ledger connected)
4. Search for issue 432
5. See error

**Expected behavior**
Notaries should be able to approve the LDN.

**Screenshots**
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/16791309/781d642c-dbf8-4b3f-a660-037f932064e1)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Version: 114.0.5735.134

**Additional context**

**Comment by huseyincansoylu** [comment]
thanks for contributing, this should be fixed by now , please check it and let us know @jamerduhgamer
