### ISSUE TITLE
LDN Notary Public Unable to Complete Signature

### ISSUE THREAD

**Issue by shenfan12345** [keyko-io/filecoin-verifier-frontend#795]
Hello, my LDN still cannot display the code in the notary's signature and cannot be signed. Please support. Thank you
![7084477E-3EE1-4311-BB28-7F0C4F4B3113](https://github.com/keyko-io/filecoin-verifier-frontend/assets/126555126/8d618b56-4d5b-4d01-8330-5166049c3b13)

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1732

**Comment by huseyincansoylu** [comment]
this should be fixed , please check it and let us know @shenfan12345
