### ISSUE TITLE
[ Bug Report ] no assignees to applications

### ISSUE THREAD

**Issue by kevzak** [keyko-io/filecoin-verifier-frontend#803]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2085

Normal assignees (Galen, RG, KWray) are not being added to new application. Also labels not added.

**Comment by fabriziogianni7** [comment]
ok, the bot was down. we implemented the healthckeck.
waiting for the guys to approve
https://github.com/keyko-io/filecoin-verifier-backend/pull/20
https://github.com/keyko-io/filecoin-large-clients-onboarding-bot/pull/170

@ssallam @jbesraa @huseyincansoylu
