### ISSUE TITLE
Registry:  Notary Verification Failing

### ISSUE THREAD

**Issue by Kevin-FF-USA** [keyko-io/filecoin-verifier-frontend#805]
**Describe the bug**
Impacting individual notary, not all.
Receiving Verification Failed: Invalid secp256k1 address length
Notary reporting: ZcFil (https://github.com/filecoin-project/notary-governance/issues/643)

**To Reproduce**
Registry 

<img width="1050" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/94004586/c0a1d6e4-591a-4de4-911c-e5e78d75ec7b">

**Comment by Aaron01230** [comment]
It is very strange that after the wallet address of 1937 is masked, the displayed length is 8, and the displayed length of other LDNs is 9
<img width="762" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/107668727/5ecc5aef-7128-4837-bf60-81623476f720">
<img width="889" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/107668727/8949aa3f-b786-4194-b94e-90641557b826">

**Comment by fabriziogianni7** [comment]
@Kevin-FF-USA can we know what ledger and ledger version notaries are using?
can we also know on which gothub issue is this bug happening?

**Comment by Aaron01230** [comment]
> @Kevin-FF-USA can we know what ledger and ledger version notaries are using? can we also know on which gothub issue is this bug happening?
ledger version is 
<img width="569" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/107668727/7463c6d8-a128-4529-8349-92c9bf2598e0">

and github issue is [#1937](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1937)

**Comment by fabriziogianni7** [comment]
> > @Kevin-FF-USA can we know what ledger and ledger version notaries are using? can we also know on which gothub issue is this bug happening?
> > ledger version is
> 
> <img alt="image" width="569" src="https://user-images.githubusercontent.com/107668727/255456909-7463c6d8-a128-4529-8349-92c9bf2598e0.png">
> and github LDN issue is #1937

what is the version of your filecoin app? that can be an issue related with your ledger

**Comment by Aaron01230** [comment]
> > > @Kevin-FF-USA can we know what ledger and ledger version notaries are using? can we also know on which gothub issue is this bug happening?
> > > ledger version is
> > 
> > 
> > <img alt="image" width="569" src="https://user-images.githubusercontent.com/107668727/255456909-7463c6d8-a128-4529-8349-92c9bf2598e0.png">
> > and github LDN issue is #1937
> 
> what is the version of your filecoin app? that can be an issue related with your ledger

the version of your filecoin app is v0.22.5

**Comment by fanjingar** [comment]
<img width="970" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/130625217/a5c7742e-a251-4813-aa41-986ba51221b8">
@fabriziogianni7

**Comment by fanjingar** [comment]
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/130625217/f5021e9f-4ce1-4aea-b4e8-4241dc43ea04)

**Comment by Aaron01230** [comment]
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/107668727/f211f780-6554-493b-aa68-2059921152b1)

**Comment by fanjingar** [comment]
When will this bug be fixed? we've been delayed for a week

**Comment by fanjingar** [comment]
@huseyincansoylu  pls help me ASAP, thanks

**Comment by jbesraa** [comment]
hey @fanjingar sorry for the delay here - will try to get this done next week.

**Comment by Kevin-FF-USA** [comment]
Friendly check in on this.
The 4th rd Notary cycle will be ending in a few weeks.  Sending DM's to Zcfil Consortium to see if this is still a need, or if they wish to apply for Allocators

**Comment by clriesco** [comment]
Closed due to inactivity
