### ISSUE TITLE
Bot is not triggering next DataCap allocation after 2 notaries have signed

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#808]
**Describe the bug**
The bot is not triggering the next DataCap allocation after 2 notaries have signed in the client's LDN application

**To Reproduce**
Go to client's application and look at the very bottom of the issue
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/995

**Expected behavior**
After the 2 notaries have signed and approved, the bot should show that the client has received the next allocation

**Comment by fabriziogianni7** [comment]
After debugging, the issue is that the template for the issue is the old one and it's missing maby informations.
Please @simonkim0515, can you tell the client to open a new issue using the latest template?
