### ISSUE TITLE
Incorrect label added after allocation is approved

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#809]
**Describe the bug**
After a tranche is approved, the LDN GitHub issue still has “ready to sign” tag on it. This effectively causing a duplicate sized tranche ready to be signed again immediately.

**To Reproduce**
Please check this application and go towards the bottom
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050

**Expected behavior**
Should have correct labels after notaries sign

**Comment by fabriziogianni7** [comment]
@simonkim0515 
I'm seeing that the bot is posting label correctly here.
here the request: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050#issuecomment-1643507914
where the bot added ready to sign correctly. 
can you tell me the comment where the bot  failed to post the correct labels?

**Comment by huseyincansoylu** [comment]
the labels are correct, we are closing this issue.
