### ISSUE TITLE
Correct Assignees

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#810]
**Describe the bug**
E-fil+ applications should assign @kevzak and add the E-fil+ label
 
**To Reproduce**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2085

**Comment by jbesraa** [comment]
opened the bug in the bot repo as thats where it should be fixed 
https://github.com/keyko-io/filecoin-large-clients-onboarding-bot/issues/171
follow up there please

**Comment by jbesraa** [comment]
fix deployed
