### ISSUE TITLE
Allocation count incorrect

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#813]
**Describe the bug**
The allocation that the client has received went backwards, rather than getting 2x, the allocation went 0.5x

**To Reproduce**
Please look at the bottom of the application as the client has explained the issue with a screenshot
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1625

**Expected behavior**
Allocation count should 2x and not 0.5x

**Comment by fabriziogianni7** [comment]
the problem here is that https://api.datacapstats.io/public/api/getVerifiedClients returns only one allocation here. looking into it.

**Comment by jbesraa** [comment]
hey @simonkim0515 was this resolved?
