### ISSUE TITLE
[ Bug Report ] The robot does not trigger the DC

### ISSUE THREAD

**Issue by ipfscn** [keyko-io/filecoin-verifier-frontend#815]
**Describe the bug**
1009 The first round of DC has been used up, but the robot has never triggered the second round of DC, as far as I know, it has been 10 days

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1009

**Additional context**

The 1009 robot is not triggered, and the notary cannot find the 1009 in the background and cannot sign it.
Please fix it as soon as possible, thank you!

**Comment by fabriziogianni7** [comment]
https://api.datacapstats.io/public/api/getVerifiedClients does not show in the respone the address f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva

**Comment by huseyincansoylu** [comment]
we are closing this issue, since it got the trigger.
