### ISSUE TITLE
Applications not visible by notaries in registry view

### ISSUE THREAD

**Issue by kevzak** [keyko-io/filecoin-verifier-frontend#819]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2106
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2107 -  how can we fix this?

**Comment by fabriziogianni7** [comment]
So the problem solution is here --> https://github.com/keyko-io/filecoin-verifier-frontend/issues/818#issuecomment-1647611038
please put efil as identifier and re-trigger the request

**Comment by kevzak** [comment]
It’s not EFil @fabriziogianni7

**Comment by kevzak** [comment]
The client marked as public/private but changed. It’s open datasets

**Comment by fabriziogianni7** [comment]
can we close this? @kevzak
