### ISSUE TITLE
[ Bug Report ]LDN notary unable to complete signature

### ISSUE THREAD

**Issue by cqh2022** [keyko-io/filecoin-verifier-frontend#821]
**Describe the bug**
The LDN link is as follows:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1236
**To Reproduce**
![2222222222](https://github.com/keyko-io/filecoin-verifier-frontend/assets/116540903/b8e87236-ade7-4f30-af8e-7fe218df1a0f)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fabriziogianni7** [comment]
have a look here:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1236#issuecomment-1650834062

**Comment by simonkim0515** [comment]
Seems like this is not complete. Reopening
