### ISSUE TITLE
NOTARY Registry - IPFS Japan Consortium 

### ISSUE THREAD

**Issue by Kevin-FF-USA** [keyko-io/filecoin-verifier-frontend#822]
**Describe the bug**
approved Notary address is supposed to display more than 1 PB of datacap allowance. We can validate on-chain that it was given to us, but somewhere down the line - perhaps an RKH issue -- it never shows on the Registry.  

**To Reproduce**
<img width="633" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/94004586/4edef655-5163-4d3e-8c00-6437ede3744a">

https://www.loom.com/share/8414d92df949431d834efb8b3f5be459

**Expected behavior**
clients assigned 

**Screenshots**
<img width="1174" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/94004586/6a3ce347-343b-402b-b2b5-71679d8cce74">

**Additional context**
[Add any other context about the problem here.](https://github.com/filecoin-project/notary-governance/issues/696)
https://github.com/MasaakiNawatani

@philippbanhardt

**Comment by Kevin-FF-USA** [comment]
Friendly check in on this.
The 4th rd Notary cycle will be ending in a few weeks.  Sending DM's to IPFS Consortium to see if this is still a need, or if they wish to apply for Allocators

**Comment by clriesco** [comment]
Is this issue still pending to be resolved?

**Comment by clriesco** [comment]
Closed due to inactivity
