### ISSUE TITLE
Ledger Cannot Approve Private DataCap[ Bug Report ]

### ISSUE THREAD

**Issue by KodaRobotDog** [keyko-io/filecoin-verifier-frontend#825]
**Describe the bug**
When I try to approve private request of datacap from my notary ledger backend, I was not able to and had an error message 

**To Reproduce**
1. Log in Ledger Notary
2. Click on 'Approve Private Request', Fill out all the blanks 
3. Click on 'Send Request'

**Expected behavior**
An error message appear at the bottom left of the browser screen (refer to screenshot).

**Screenshots**
<img width="562" alt="Screenshot 2023-07-26 at 11 21 48" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/71876834/56dfcc81-bee5-4d3a-b7c3-3c881077b4d3">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: most updated

**Comment by jbesraa** [comment]
hey @KodaRobotDog are u still facing this problem?

**Comment by clriesco** [comment]
Either notary is a verifier or hasn't enough funds in wallet
