### ISSUE TITLE
Notary Address Verification Failed [ Bug Report ]

### ISSUE THREAD

**Issue by KodaRobotDog** [keyko-io/filecoin-verifier-frontend#826]
**Describe the bug**
My notary address (f1wd5jgnhc2gqr35446lrp3lmilkmri26nerb2n4q) cannot be verified from my notary ledger backend. 

**To Reproduce**
1. Log in Notary account via ledger
2. Click on 'Verify client'
3. Click 'Accept'
4. Next to 'Verify new datacap', there are three dots that probably indicated the next step is loading / in progress that goes on forever

**Expected behavior**
Loading should not take that long. 

**Screenshots**
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/71876834/baf04468-1520-4de3-bf35-eb0bd6b0577e)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Browser 
 - Version: Up-to-date

**Comment by jbesraa** [comment]
hey @KodaRobotDog are u still having this problem?
