### ISSUE TITLE
[ Bug Report ] The robot does not trigger the DC！

### ISSUE THREAD

**Issue by XindyTan** [keyko-io/filecoin-verifier-frontend#828]
**Describe the bug**
There is only 44T left in the last round, but the but the robot has never triggered the next round of DC yet. As far as I know, it has been few months.

![img_v2_97d907d9-1641-4cb4-83ba-b9ca2522507g](https://github.com/keyko-io/filecoin-verifier-frontend/assets/112474743/3d02e1ce-3efd-4f00-a62a-ac8a0dbcf095)

**Link to my issue：**https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1293

**Additional context**
The robot is not triggered, and the notary cannot find the bot in the background and cannot sign it.
Please fix it as soon as possible, thank you!

**Comment by XindyTan** [comment]
Hey @fabriziogianni7  @kevzak   @simonkim0515  @Kevin-FF-USA, 
Can someone help fix this problem? We need the quota urgently. When can you guys fix it? Thanks

**Comment by huseyincansoylu** [comment]
@XindyTan It should be ok now, I also commented in the issue, we just need to wait the bot trigger new one.

**Comment by huseyincansoylu** [comment]
I am closing this one since its fixed. @XindyTan  

thanks for the contribution.
