### ISSUE TITLE
notary able to sign with governance tag on

### ISSUE THREAD

**Issue by Filplus-govteam** [keyko-io/filecoin-verifier-frontend#830]
**Describe the bug**
[A clear and concise description of what the bug is.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1045#issuecomment-1657198373)

example where governance needed tag was enabled but notary was still able to sign. This should be a blocker from signing. 

Also the bot removed the label later

**Comment by huseyincansoylu** [comment]
I have created pr for this fix @Filplus-govteam

**Comment by jbesraa** [comment]
PR merged , should be in production soon.
