### ISSUE TITLE
[ Bug Report ] 1955 and 2087 did not trigger new allocation

### ISSUE THREAD

**Issue by xinaxu** [keyko-io/filecoin-verifier-frontend#834]
**Describe the bug**
Below two LDN issues did not have new allocation triggered
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1955
* Last allocation 2PiB
* Remaining datacap 300.875 TiB
* Remaining ratio 15%

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2087
* Last allocation 512TiB
* Remaining datacap 105.7TiB
* Remaining ratio 20.6%

**Comment by huseyincansoylu** [comment]
it looks like something went wrong with labels, i have adjusted them, now it should be ok. @xinaxu

**Comment by huseyincansoylu** [comment]
I am closing this one since its fixed. @xinaxu  

thanks for the contribution.
