### ISSUE TITLE
[ Bug Report ] The robot does not trigger the DC

### ISSUE THREAD

**Issue by 1613557499** [keyko-io/filecoin-verifier-frontend#836]
**Describe the bug**
The notary has completed the signature, but the 400T limit has not been issued, resulting in SP unable to carry out the invoice encapsulation, please deal with it as soon as possible.

<img width="1363" alt="微信图片_20230803162013" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/86406225/4303ff4f-bacf-4ac1-bf49-49691d937a5f">
<img width="876" alt="微信图片_20230803162024" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/86406225/571115c5-4702-42d1-bf5b-445c25548d78">

**Comment by huseyincansoylu** [comment]
since the issue got the new request , we are closing this.

thanks for the contribution. @1613557499
