### ISSUE TITLE
Stale label is added before the application is closed

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#839]
**Describe the bug**
The "Stale" label is being added to applications that have received the warning message from the github-actions bot.

**To Reproduce**
 Go to ['...'](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2102) and see github-actions bot comment.

**Expected behavior**
When a client's application is inactive after 14 days the application should close and be given the Stale label. Each application will get a warning message after 10 days if there are no comments, but no label should be added. 
 
**Screenshots**

<img width="1001" alt="Screen Shot 2023-08-08 at 11 26 27 AM" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/59632896/b48a2465-a7f0-47b0-93f5-50d4a28c0d4d">

**Comment by clriesco** [comment]
Done: https://github.com/keyko-io/filecoin-large-clients-onboarding/pull/1608
