### ISSUE TITLE
[ DC quota assignment error / DC robot not triggering]

### ISSUE THREAD

**Issue by AlanGreaterheat** [keyko-io/filecoin-verifier-frontend#842]
**Describe the bug**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2029
1. The round of DC quota issuance is not correct, we issued 512 TiB in the first round, according to the reason, it should be 1024 TiB in the second round, but still issued 512 TiB.
2. For the second round of 512 TiB DC, we have sealed 85%, but still no bots are triggered.

https://datacapstats.io/clients/f02211290

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbesraa** [comment]
Hey, there is currently a problem in the filecoin api and we are waiting for response from that team to able to solve this. will get back to you as soon as its resolved.

**Comment by jbesraa** [comment]
Closing as the bot is back running
