### ISSUE TITLE
[ Bug Report ]The bot is not working, the quota is not triggered

### ISSUE THREAD

**Issue by nicelove666** [keyko-io/filecoin-verifier-frontend#844]
The bot is not working, the DC quota is not triggered, It's been 2 days
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2045
Please help to manually trigger, thanks！

**Comment by jbesraa** [comment]
Hey, there is currently a problem in the filecoin api and we are waiting for response from that team to able to solve this. will get back to you as soon as its resolved.

**Comment by nicelove666** [comment]
Hey, @jbesraa,The bot at 2045 didn't work again, the bot didn't trigger the next round
