### ISSUE TITLE
[ Bug Report ] bot not triggered

### ISSUE THREAD

**Issue by xinaxu** [keyko-io/filecoin-verifier-frontend#845]
**Describe the bug**
The bot did not trigger despite DC is depleted
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1955
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2087

f1l2cc5vuw5moppwsjd3b7cjtwa2exowqo36esklq: 260 TiB left
f1fjegj5ihpjn5ie75np6vagpwbvx3je4ni2ve4iq: 26 TiB left

**Comment by jbesraa** [comment]
Hey, there is currently a problem in the filecoin api and we are waiting for response from the team to able to solve this. will get back to you as soon as its resolved.

**Comment by jbesraa** [comment]
I am closing this it looks like resolved.
