### ISSUE TITLE
[ Bug Report ]The bot large-datacap-requests error 

### ISSUE THREAD

**Issue by jhyehuang** [keyko-io/filecoin-verifier-frontend#846]
**Describe the bug**
The large-datacap-request bot goes wrong with BUG as following.
![img_v2_ed518660-d6ec-4155-b3aa-e1f8dbf120cg](https://github.com/keyko-io/filecoin-verifier-frontend/assets/14520654/014b9fb9-0066-41f7-a30e-19f645a1f448)

Please check [[DataCap Application] Beijing Yuanshu Landscape Planning and Design Office · Issue #958 · filecoin-p](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/958)

**Comment by clriesco** [comment]
A bot instance in the staging environment interfered with the production environment.
