### ISSUE TITLE
[ Bug Report ] tranche not kicking off

### ISSUE THREAD

**Issue by panges2** [keyko-io/filecoin-verifier-frontend#847]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1813
The next datacap tranche isn't kicking off but they are out of datacap

**Comment by jbesraa** [comment]
Application need two notaries to sign the latest request

**Comment by jamerduhgamer** [comment]
@jbesraa, @panges2, it looks like notaries are unable to sign the latest request.
![Scherm_afbeelding 2023-08-25 om 22 09 31](https://github.com/keyko-io/filecoin-verifier-frontend/assets/16791309/153cbcd4-1b62-411b-84a2-4112722278f4)
