### ISSUE TITLE
[ Bug Report ]bot not working

### ISSUE THREAD

**Issue by ssnks1** [keyko-io/filecoin-verifier-frontend#848]
The bot didn't work,  when the first round of DC was used up, the bot didn't trigger the quota.

Now, the bot should need to trigger the 3rd round of 1P or 2P, however, bot didn't work.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2108

**Comment by ssnks1** [comment]
@jbesraa  The DC ran out, but the bot didn't trigger, can you make the bot work？ it seems, the bot needs to trigger 1P

**Comment by jbesraa** [comment]
I need to understand first why the notary started the second allocation without the bot triggering it

**Comment by ssnks1** [comment]
Because https://filplus.fil.org/#/ can see 2108

**Comment by ssnks1** [comment]
This bug has appeared many times:

The bot is not triggered, signatures can still be signed in the [signature background of the notary,](https://filplus.fil.org/#/),  but the quota of the signature is still the quota of the previous round.

**Comment by ssnks1** [comment]
@jbesraa The bot looks like it hasn't worked for two days, we've been waiting for the bot to trigger the next round of quota, but the bot doesn't, can you help us,thanks a lot！
