### ISSUE TITLE
[ Bug Report ] The bot is not working

### ISSUE THREAD

**Issue by nicelove666** [keyko-io/filecoin-verifier-frontend#850]
The bot is not working, the DC quota is not triggered, It's been 2 days
[2045]
Please help to manually trigger, thanks！
#844

**Comment by nicelove666** [comment]
@jbesraa Is there any update here,  can you help me trigger it manually? thanks a lot!  https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2045

**Comment by clriesco** [comment]
Margin quota over 25%. At this moment DC allocation should not be triggered in this application
