### ISSUE TITLE
[ LDN #1198 Notary has signed, but 800 TiB DC quota has not yet been issued ]

### ISSUE THREAD

**Issue by jacktree7** [keyko-io/filecoin-verifier-frontend#853]
**Describe the bug**

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1198
LDN #1198 Notary has signed, but 800 TiB DC quota has not yet been issued

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1404" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/116623999/5a71e549-42f2-4346-9b96-b1b9c09c2c0c">

<img width="1439" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/116623999/97712edc-014f-414f-bc06-c3366f7c7682">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clriesco** [comment]
The bot has not been active due to an API outage. It should have been resolved 4 days ago.
