### ISSUE TITLE
[ Bug Report ] LDN 2100 Robot did not trigger quota approval and the next round of quota triggering approval

### ISSUE THREAD

**Issue by hash889900** [keyko-io/filecoin-verifier-frontend#855]
**Describe the bug**
[LDN 2100](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2100)
Robot did not trigger quota approval and the next round of quota triggering approval

**Screenshots**

![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/138882650/5bd60a34-1df4-47aa-95b7-d4a9d17348a0)

**Comment by hash889900** [comment]
@jbesraa  It should have triggered the second signature by now，Should be in signable status，Please look again,thank you

**Comment by hash889900** [comment]
One of the notaries signed the first sign of the second round, and it looks like there's still no bot trigger

**Comment by clriesco** [comment]
The bot has not been active due to an API outage. It should have been resolved two days ago.
