### ISSUE TITLE
[ Bug Report ]The bot [large-datacap-requestscreate] create datacap allocation requested automatically

### ISSUE THREAD

**Issue by Sunnyiscoming** [keyko-io/filecoin-verifier-frontend#856]
**Describe the bug**
The bot large-datacap-requests create DataCap Allocation requested automatically

**To Reproduce**
1. Go to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2163
2. See error https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2163#issuecomment-1704365279

**Screenshots**
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/105098820/2e8b5528-6cd7-45ca-8170-0fe97260b3c7)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  chrome
 - Version 116.0.5845.42

**Comment by clriesco** [comment]
I have searched in the logs and there is nothing at that hour. That means that this has been triggered manually from the frontend

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2196

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2198

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2184
Next round of datacap allocation requested was not created automatically.

**Comment by Sunnyiscoming** [comment]
Any update here？

**Comment by clriesco** [comment]
The Dmob API was down, so SSA bot couldn't do its work. It was solved after sept 25

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2179#issuecomment-1764536651

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2229
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2232
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2233
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2241
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2243
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2244
@clriesco Please look at these issues. Same problem happened.

**Comment by clriesco** [comment]
@Sunnyiscoming Plz, let's talk about it on Slack.

**Comment by Sunnyiscoming** [comment]
My slack handle: Laura Laura

**Comment by jevticgallonsd1466** [comment]
@clriesco  Hello. Is this bug being addressed? How long will it approximately take to resolve it?

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2234

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2233

**Comment by clriesco** [comment]
Solved and triggered

**Comment by FroghubMan** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2243
@clriesco  Not triggered yet....
