### ISSUE TITLE
Incoming LDN applications coming in WITHOUT labels

### ISSUE THREAD

**Issue by simonkim0515** [keyko-io/filecoin-verifier-frontend#858]
**Describe the bug**
New incoming LDN applications are coming in without labels getting attached to them. Whenever applications come in, they should automatically have labels.

**To Reproduce**
1. Go to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues
2. Click on applications 2213, 2212, 2210, 2207, 2205

**Screenshots**
<img width="1543" alt="Screen Shot 2023-09-20 at 1 42 56 PM" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/59632896/73ce37f2-ba9c-4690-b4a5-3f557639b249">

**Comment by panges2** [comment]
@simonkim0515 the above application seems to all have their labels. Closing this one out

**Comment by panges2** [comment]
@simonkim0515 the above application seems to all have their labels. Closing this one out
