### ISSUE TITLE
[ Bug Report ] SSA bot watching the LDN multisig didn’t trigger for top-up from RKH

### ISSUE THREAD

**Issue by Kevin-FF-USA** [keyko-io/filecoin-verifier-frontend#860]
**Describe the bug**
SSA bot watching the LDN multisig didn’t trigger for top-up from RKH

https://github.com/filecoin-project/notary-governance/issues/836

**Additional context**
For Additional points of context - @panges2 @galen-mcandrew

**Comment by panges2** [comment]
Assuming this is fixed now, closing out
