### ISSUE TITLE
[ Bug Report ] Retrieval Bot displayed success rate is lower than actual

### ISSUE THREAD

**Issue by hongyandeshuaige** [keyko-io/filecoin-verifier-frontend#861]
**Describe the bug**
![img_v2_592993f6-19b2-47d5-b033-4b8d7ac6af5g](https://github.com/keyko-io/filecoin-verifier-frontend/assets/18166821/bc11f8b5-97a2-4e64-94f4-0edc92f40bc3)

The current real retrieval rate should be >70%, but the displayed retrieval rate of the robot is never updated, and some SPs are not included in the retrieval report, such as f02809374 .
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/18166821/ae1d2baf-c9d4-4160-8a07-a4684baa75f1)

I manually performed a retrieval test on datacid=bafybeiagi34way274j47k4hgnukizpwhx27rgxgm7xcrhnaunpnlyrzeya, and the results are as follows:
····
$ lotus client retrieve --provider f02809374 bafybeiagi34way274j47k4hgnukizpwhx27rgxgm7xcrhnaunpnlyrzeya 1.car          
Recv 0 B, Paid 0 FIL, Open (New), 0s [1695275311532383700|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1695275311532383700|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 251ms [1695275311532383700|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 251ms [1695275311532383700|0]
Recv 5.968 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 391ms [1695275311532383700|6111]
Recv 7.295 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 393ms [1695275311532383700|7470]
Recv 1.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.598s [1695275311532383700|1056046]
Recv 2.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2.142s [1695275311532383700|2104622]
Recv 3.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2.459s [1695275311532383700|3153198]
Recv 4.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3.105s [1695275311532383700|4201774]
Recv 5.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3.407s [1695275311532383700|5250350]
Recv 6.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3.807s [1695275311532383700|6298926]

$ lotus client retrieve --provider f02191111 bafybeiagi34way274j47k4hgnukizpwhx27rgxgm7xcrhnaunpnlyrzeya 2.car         
Recv 0 B, Paid 0 FIL, Open (New), 0s [1695275311532383703|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms [1695275311532383703|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 134ms [1695275311532383703|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 134ms [1695275311532383703|0]
Recv 5.968 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.067s [1695275311532383703|6111]
Recv 7.295 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.069s [1695275311532383703|7470]
Recv 1.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.101s [1695275311532383703|1056046]
Recv 2.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.133s [1695275311532383703|2104622]
Recv 3.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.144s [1695275311532383703|3153198]
Recv 4.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.22s [1695275311532383703|4201774]
Recv 5.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.234s [1695275311532383703|5250350]
Recv 6.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.243s [1695275311532383703|6298926]
Recv 7.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.256s [1695275311532383703|7347502]

$ lotus client retrieve --provider f02809382 bafybeiagi34way274j47k4hgnukizpwhx27rgxgm7xcrhnaunpnlyrzeya 3.car         
Recv 0 B, Paid 0 FIL, Open (New), 1ms [1695275311532383704|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1695275311532383704|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 820ms [1695275311532383704|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 820ms [1695275311532383704|0]
Recv 5.968 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.445s [1695275311532383704|6111]
Recv 7.295 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.455s [1695275311532383704|7470]
Recv 1.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 21.695s [1695275311532383704|1056046]
Recv 2.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 40.909s [1695275311532383704|2104622]
Recv 3.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 54.587s [1695275311532383704|3153198]
Recv 4.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m15.353s [1695275311532383704|4201774]
Recv 5.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m30.959s [1695275311532383704|5250350]
Recv 6.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m48.532s [1695275311532383704|6298926]

$ lotus client retrieve --provider f02195555 bafybeiagi34way274j47k4hgnukizpwhx27rgxgm7xcrhnaunpnlyrzeya 4.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1695275311532383708|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1695275311532383708|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 159ms [1695275311532383708|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 159ms [1695275311532383708|0]
Recv 5.968 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.643s [1695275311532383708|6111]
Recv 7.295 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.656s [1695275311532383708|7470]
Recv 1.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.708s [1695275311532383708|1056046]
Recv 2.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.721s [1695275311532383708|2104622]
Recv 3.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.74s [1695275311532383708|3153198]
Recv 4.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.764s [1695275311532383708|4201774]
Recv 5.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.799s [1695275311532383708|5250350]
Recv 6.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.825s [1695275311532383708|6298926]
Recv 7.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.852s [1695275311532383708|7347502]
Recv 8.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.879s [1695275311532383708|8396078]
Recv 9.007 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.908s [1695275311532383708|9444654]
Recv 10.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.931s [1695275311532383708|10493230]
Recv 11.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.972s [1695275311532383708|11541806]
····

![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/18166821/9f28ff15-ab2f-49e8-a8ba-1f539b826b27)

**To Reproduce**
1. Go to ['...'](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2170)
2. Click retrival report or dashboard, and compare with CID checker report
3. See error

**Comment by hongyandeshuaige** [comment]
![img_v2_4eff29d2-b27a-45a2-80d9-08ad1f5ad59g](https://github.com/keyko-io/filecoin-verifier-frontend/assets/18166821/834f31d7-96ed-4fc7-9d3f-fe436a38331f)
I can confirm that f02809374 is 100% retrievalable, this is the retrieval report of this miner in other Clients.

**Comment by clriesco** [comment]
Is this issue pending to be resolved, @hongyandeshuaige ?

**Comment by clriesco** [comment]
Got no response from user
