### ISSUE TITLE
[ Bug Report ]

### ISSUE THREAD

**Issue by PicasMix** [keyko-io/filecoin-verifier-frontend#864]
**Describe the bug**
During the process of distributing the second 200TiB deal data, the notary(@dannyob) helped me sign and add a "start to sign" label. After the distribution of the 200TiB deal data, the robot did not automatically trigger the third request, resulting in my LDN not being able to proceed.

**To Reproduce**
N/A

**Expected behavior**
Trigger the third request so that my LDN can proceed normally.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
[LDN #1561](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1561)

**Comment by clriesco** [comment]
As I am seeing, application has "ready to sign" state. In fact, last datacap tranch has been proposed but not approved, so SSA bot should not act here.
Bot behavior is correct

**Comment by PicasMix** [comment]
> As I am seeing, application has "ready to sign" state. In fact, last datacap tranch has been proposed but not approved, so SSA bot should not act here. Bot behavior is correct

Hi @clriesco ,
The request 2(id:39569b02-9c51-4664-b2f7-99563f123421) has already been approved, why can it still be proposed twice.

**Comment by panges2** [comment]
Seems like this is fixed. Closing this out!
