### ISSUE TITLE
 #1732 Robot Manual Trigger

### ISSUE THREAD

**Issue by Paris-Spring** [keyko-io/filecoin-verifier-frontend#865]
**Describe the bug**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1732

<img width="1435" alt="c76aa50f5be5ed8ffdf72d04f019e5e" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/126555613/33d3409b-1f20-4039-bc1b-412c796f89a6">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by panges2** [comment]
This is not a SA bot/LDN bot tooling issue. Closing this one out. ping @philippe pangestu on slack if further assistance is needed

**Comment by panges2** [comment]
This is not a SA bot/LDN bot tooling issue. Closing this one out. ping @philippe pangestu on slack if further assistance is needed
