### ISSUE TITLE
[ Bug Report ] retrieval rate 0% bug

### ISSUE THREAD

**Issue by FroghubMan** [keyko-io/filecoin-verifier-frontend#867]
**Describe the bug**
About #2117. The problem we encountered was that the retrieval rate from the machine feedback was 0%. But in fact all of these SPs support retrieval.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clriesco** [comment]
Is this issue still pending to be resolved @FroghubMan ?

**Comment by clriesco** [comment]
Got no response from user
