### ISSUE TITLE
Notary cannot find the target LDN in searched with ID

### ISSUE THREAD

**Issue by woshidama323** [keyko-io/filecoin-verifier-frontend#873]
**Describe the bug**
Notary cannot find the target LDN in searched with ID

**To Reproduce**
![5451699413627_ pic](https://github.com/keyko-io/filecoin-verifier-frontend/assets/11014169/73c110a1-c9ae-43af-a179-26e93a340371)

![5461699413639_ pic](https://github.com/keyko-io/filecoin-verifier-frontend/assets/11014169/e376fac7-d15d-40e4-9282-3c7b6f485955)

**Expected behavior**
Notary could find the LDN and can approve

**Screenshots**
same above

**Desktop (please complete the following information):**

chrome
119.0.6045.105

**Additional context**
N/A

**Comment by clriesco** [comment]
Automatic comment by bot was not present at the time. Now everything works correctly
