### ISSUE TITLE
[ Bug Report ]The robot is not working

### ISSUE THREAD

**Issue by shuchenglhk** [keyko-io/filecoin-verifier-frontend#876]
[[DataCap Application] National Radio Astronomy Observatory](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2260#top)
#2260

The robot is not working，Notary cannot sign in the background.Please help us trigger manually

**Comment by clriesco** [comment]
Ldn bot was down by the time this was triggered, so it couldn't apply proper tags
