### ISSUE TITLE
The robot is not working [ Bug Report ]

### ISSUE THREAD

**Issue by caokun8341** [keyko-io/filecoin-verifier-frontend#877]
**Describe the bug**
The robot is not working 

**To Reproduce**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1346
Our LDN, after the completion of 400T data storage, the robot should give 800T a new quota, but the current situation is that after the 400T quota is used up, the robot will not pop up the new quota, and the new quota seen in the background is still 400T, please help us repair it as soon as possible, thank you!

**Expected behavior**
please help us repair it as soon as possible, thank you!

**Comment by clriesco** [comment]
At the time the SSA BOT had to configure the third tranche, DMOB API only returned the first tranche, so the calculations were made based on that response
