### ISSUE TITLE
Issue with DataCap without being triggered

### ISSUE THREAD

**Issue by Filplus-govteam** [keyko-io/filecoin-verifier-frontend#883]
**Describe the bug**
Something happened where the application has DataCap but no trail of being triggered or allocation 1 either. (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2270)

**Comment by clriesco** [comment]
Previous issue existing with same address: 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1440
