### ISSUE TITLE
[ Bug Report ] not trigger robot

### ISSUE THREAD

**Issue by mingyang313** [keyko-io/filecoin-verifier-frontend#885]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1365
not datacap,but not trigger robot

**Comment by mingyang313** [comment]
1

**Comment by mingyang313** [comment]
1

**Comment by clriesco** [comment]
The application was Ready to Sign by the time this issue was opened, so the bot didn't act on this.
Closing.
