### ISSUE TITLE
[ Bug Report ] wrong label cannot be signed

### ISSUE THREAD

**Issue by dos2un1x** [keyko-io/filecoin-verifier-frontend#888]
**Describe the bug**
wrong label cannot be signed

**To Reproduce**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2249

**Expected behavior**
please help fix it.

**Screenshots**
![image](https://github.com/keyko-io/filecoin-verifier-frontend/assets/34907247/34cdd574-1ae2-4543-9ebb-95f32fe68d25)

**Comment by clriesco** [comment]
Fixed
