### ISSUE TITLE
[ Bug Report ]Quota Exhaustion Robot Not Triggered / Notary Unable to Sign #2311

### ISSUE THREAD

**Issue by himomo007** [keyko-io/filecoin-verifier-frontend#892]
**Describe the bug**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2311

1. Meanwhile, the notary told me that he was unable to sign and could not find the corresponding LDN code
<img width="1427" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/144330825/8ca67869-f9f1-4382-8256-8d138ee907d6">

2.  The quota has been used up, only 12.1 TiB left,but the bot is not recognizing the trigger
<img width="1036" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/144330825/6014f06f-1dc1-483e-9b6a-412e3cd33b6c">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clriesco** [comment]
We're reviewing this, will come with more information soon

**Comment by himomo007** [comment]
> We're reviewing this, will come with more information soon

@clriesco Hopefully this can be resolved soon, thank you very much！

**Comment by clriesco** [comment]
All systems up and running
