### ISSUE TITLE
[ Bug Report ] The quota is about to run out, but the bot is not triggered #2265

### ISSUE THREAD

**Issue by Laycuicui** [keyko-io/filecoin-verifier-frontend#893]
**Describe the bug**

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2265

<img width="1410" alt="image" src="https://github.com/keyko-io/filecoin-verifier-frontend/assets/149811699/d60d5424-2493-4341-b56c-a441560f9c9a">

The quota is about to run out, but the bot is not triggered #2265

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clriesco** [comment]
We're reviewing this, will come with more information soon

**Comment by clriesco** [comment]
All systems up and running
